apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: My CRA Template
  title: Custom template
  description: A custom Create React App template
  tags:
    - React
    - CRA
    - Custom
  maintainer:
    name: James Mathews
    email: jamesm553@gmail.com
scaffolder:
  steps:
    - id: install-dependencies
      name: Install Dependencies
      command: yarn install
instructions:
  - title: Getting Started
    content: |
      1. Clone this project.
      2. Run `yarn install` to install dependencies.
      3. Customize the project as needed.
      4. Start the development server with `yarn start`.
dependencies:
  - name: react
    version: ^17.0.1
  - name: react-dom
    version: ^17.0.1
