apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-cra-template
  title: Custom template
  description: A custom Create React App template
  tags:
    - react
    - CRA
    - custom
spec:
  owner: jamesm553@gmail.com
  type: website
  parameters:
    - title: information
      required;
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
          allowedHosts:
            - github.com
  steps:
    - id: install-dependencies
      name: Install Dependencies
      command: yarn install